### ISSUE TITLE
Upgrade graphics-ts to fp-ts v2.x

### ISSUE THREAD

**Issue by IMax153** [gcanti/graphics-ts#6]
### Current Behavior

Hey @gcanti, first off I just wanted to say thank you for the ecosystem that you have created around functional programming in TypeScript. Your libraries/blog posts have inspired me to learn more about Category Theory as well as the functional programming paradigm. 

Currently, `graphics-ts` is implemented using `fp-ts` version `1.x`. To better learn how to use `fp-ts`, I [re-implemented](https://github.com/IMax153/dls/tree/master/packages/graphics) `graphics-ts` using `fp-ts` version `2.x`. 

I would like to open a PR to port `graphics-ts` over to `fp-ts` version `2.x` and add a comprehensive test suite to the library. However, I have not yet ported over the `free-canvas` module since I wanted to make sure that this was a contribution you were interested in first.

Please let me know if you think this would be beneficial, and I will go ahead an open a PR!

### Desired Behavior

Port `graphics-ts` over to `fp-ts` version `2.x`.

### Suggested Solution

I would like to suggest that you allow me to open a PR updating `graphics-ts` to use `fp-ts` version `2.x`. In addition, I would like to add a comprehensive test suite for the library.

You can view my implementation [here](https://github.com/IMax153/dls/tree/master/packages/graphics) including the test suite. 

### Who does this impact? Who is this for?

Users of `graphics-ts`.

### Describe alternatives you've considered

Leaving the library alone.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.6.1 |
| TypeScript | 3.9.2 |

**Comment by gcanti** [comment]
> Your libraries/blog posts have inspired me to learn more about Category Theory as well as the functional programming paradigm.

Nice! I'm glad the hear that.

> Please let me know if you think this would be beneficial, and I will go ahead an open a PR!

Sure, thanks!

> I have not yet ported over the free-canvas 

Currently there's no `Free` module in the `2.x` core, honestly I wouldn't port `free-canvas` (which was more like an experiment back then)
